# Generated by Django 4.2 on 2024-03-06 12:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2024, 3, 6, 12, 27, 6, 470180, tzinfo=datetime.timezone.utc), unique=True, verbose_name='url'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='file',
            name='slug',
            field=models.SlugField(verbose_name='url'),
        ),
    ]
