# Generated by Django 4.2 on 2024-03-07 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_file_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'video'), (2, 'pdf'), (3, 'audio')], default=2, verbose_name='file_type'),
        ),
    ]
